name: Update ASN and IP List

on: 
  push:
    paths:
      - 'scripts/**'
  workflow_dispatch:
  schedule:
    - cron: "15 15 * * *"  # 每天北京时间晚上11点15分触发

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install requests lxml

      - name: Run IP Update Script
        run: |
          source venv/bin/activate
          python scripts/ChinaIP.py
        continue-on-error: true

      - name: Run ASN Update Script
        run: |
          source venv/bin/activate
          python scripts/ChinaASN.py
        continue-on-error: true

      - name: Check for errors
        if: failure()
        run: echo "Error occurred while running scripts" && exit 1

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update IP and ASN Lists
