name: 更新 ASN 和 IP 列表

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *" # 每天 UTC 时间 23:00

permissions:
  contents: write

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 设置 Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml
      - name: 运行脚本
        run: |
          python scripts/ChinaIP.py
          python scripts/ChinaASN.py
      - name: 提交更新
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "更新 IP 列表和 ASN 列表"
